### ISSUE TITLE
How to not render the font-awesome icon in children?

### ISSUE THREAD

**Issue by fd6130** [JurajKavka/vue-bootstrap-sidebar#5]
Hello, i want to render font-awesome icon for parent but not children in a dropdown list.

I can simply put empty string or empty array in `faIcon` and error message will show in console.

Is this the correct way to not render an icon?  Thanks.

**Comment by fd6130** [comment]
Ok the solution is put `faIcon: false`

**Comment by JurajKavka** [comment]
Hi, just don't add `faIcon` property.

```
children: [
  {
    name: 'Child Item 1',
    href: { name: 'child-item-1' },
    faIcon: ['fas', 'child']
   },
   { 
     name: 'Child Item 2', 
     href: { name: 'child-item-2' } 
   }
]
```

... second child will not have icon.

J.
